//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinePusher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<int> RoundId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> Bottles { get; set; }
        public string Delivered { get; set; }
        public string Paid { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Rounds Rounds { get; set; }
    }
}
