//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinePusher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinePusherDBEntities : DbContext
    {
        public WinePusherDBEntities()
            : base("name=WinePusherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Rounds> Rounds { get; set; }
        public virtual DbSet<Wines> Wines { get; set; }
    }
}
